source "https://rubygems.org"

# Android side uses fastlane's `supply` (upload_to_play_store) to push AABs to
# Google Play. Run `RBENV_VERSION=3.3.5 bundle install` in this directory once.
gem "fastlane"
