// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('APP_ANDROID_FIREBASE_API_KEY'),
    appId: const String.fromEnvironment('APP_ANDROID_FIREBASE_APP_ID'),
    messagingSenderId: const String.fromEnvironment(
      'APP_ANDROID_FIREBASE_MSG_SENDER_ID',
    ),
    projectId: const String.fromEnvironment('APP_ANDROID_FIREBASE_PROJECT_ID'),
    storageBucket: const String.fromEnvironment(
      'APP_ANDROID_FIREBASE_STORAGE_BUCKET',
    ),
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('APP_IOS_FIREBASE_API_KEY'),
    appId: const String.fromEnvironment('APP_IOS_FIREBASE_APP_ID'),
    messagingSenderId: const String.fromEnvironment(
      'APP_IOS_FIREBASE_MSG_SENDER_ID',
    ),
    projectId: const String.fromEnvironment('APP_IOS_FIREBASE_PROJECT_ID'),
    storageBucket: const String.fromEnvironment(
      'APP_IOS_FIREBASE_STORAGE_BUCKET',
    ),
    iosBundleId: const String.fromEnvironment('APP_IOS_FIREBASE_BUNDLE_ID'),
  );
}
